info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'

grails:
  gorm:
    logSql: true
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml

  views:
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
    default:
      codec: html

  codegen:
    defaultPackage: com.maspim
  profile: web
  plugin:
    console:
      enabled: false
    springsecurity:
      userLookup:
        userDomainClassName: com.maspim.Usuario
        authorityJoinClassName: com.maspim.UsuarioRole
      authority:
        className: com.maspim.Role
      rest:
        login:
          endpointUrl: /api/login/auth
          active: true
        token:
          validation:
            enableAnonymousAccess: true
            active: true
          storage:
            jwt:
              secret: 'D83jF#kLmZQ92*!ab9vNcuuPpqRma8tF'
              expiration: 1800000
              useSignedJwt: true
              useEncryptedJwt: false
        filterChain:
          chainMap:
            - pattern: '/api/login/**'
              filters: 'JOINED_FILTERS,-csrfFilter'
            - pattern: '/api/**'
              filters: 'JOINED_FILTERS,-exceptionTranslationFilter,-authenticationProcessingFilter,-securityContextPersistenceFilter,-csrfFilter'
            - pattern: '/**'
              filters: 'JOINED_FILTERS'
      controllerAnnotations:
        staticRules:
          - pattern: '/api/login/auth'
            access: ['permitAll']
          - pattern: '/api/login/autenticar'
            access: ['permitAll']

dataSource:
  pooled: true
  jmxExport: true
  driverClassName: com.mysql.cj.jdbc.Driver
  dialect: org.hibernate.dialect.MySQL8Dialect
  username: admin
  password: admin
  url: jdbc:mysql://localhost:3306/tribarin?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

quartz:
  autoStartup: true

environments:
  development:
    dataSource:
      dbCreate: update

  test:
    dataSource:
      dbCreate: update

  production:
    dataSource:
      dbCreate: none
      url: jdbc:mysql://localhost:3306/prodDb
      username: prodUser
      password: prodPassword
      properties:
        connectionTimeout: 30000
        idleTimeout: 60000
        jmxEnabled: true
        initialSize: 5
        maxActive: 50
        minIdle: 5
        maxIdle: 25
        maxWait: 10000
        maxAge: 600000
        timeBetweenEvictionRunsMillis: 5000
        minEvictableIdleTimeMillis: 60000
        validationQuery: SELECT 1
        validationQueryTimeout: 3
        validationInterval: 15000
        testOnBorrow: true
        testWhileIdle: true
        testOnReturn: false
        jdbcInterceptors: ConnectionState
        defaultTransactionIsolation: 2

hibernate:
  cache:
    queries: false
  dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: '1234567890abcdefghijklmnopq'
  expiration: 1800000 # 30mili

logging:
  level:
    #grails.web.mapping: DEBUG
    #org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
